version: 2
updates:
- package-ecosystem: cargo
  directory: "/cli"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[cli]"
- package-ecosystem: cargo
  directory: "/lib"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[lib]"
- package-ecosystem: cargo
  directory: "/gui"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[gui]"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
