import { TextEdit, Button } from "std-widgets.slint";

component TextInput inherits VerticalLayout {
    spacing: 5px;

    callback post_text(string);

    text_content := TextEdit {
        enabled: true;
        read-only: false;
    }

    Rectangle {
        HorizontalLayout {
            Button {
                text: "Attachments";
            }

            Button {
                text: "Cancel";

                clicked => {
                    text_content.text = "";
                }
            }

            Button {
                text: "Post";

                clicked => {
                    root.post_text(text_content.text)
                }
            }
        }
    }
}

export component Input {
    TextInput {
    }
}
