name: "Check distrox"

on:
  push:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: swatinem/rust-cache@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  # We need some "accummulation" job here because bors fails (timeouts) to
  # listen on matrix builds.
  # Hence, we have some kind of dummy here that bors can listen on
  ci-success:
    name: CI
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: CI succeeded
        run: exit 0

