name: "Check distrox"

on:
  push:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.2.0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - uses: swatinem/rust-cache@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Install Protoc
        run: sudo apt install -y protobuf

      - name: Create dist dir
        run: mkdir gui/frontend/dist

      - name: Run cargo check
        run: cargo check --all-features


  check-flake:
    name: check-flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: distrox
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix --extra-experimental-features "nix-command flakes" flake check


  test-lib:
    # depend on check-flake, because its faster than "check", so this job starts
    # sooner this way.
    needs: [check-flake]
    name: Test lib
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: ipfs/kubo
        ports:
          - 5001:5001
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.2.0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - uses: swatinem/rust-cache@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Install Protoc
        run: sudo apt install -y protobuf

      - name: Run cargo test -p distrox-lib
        env:
          IPFS_HOST_ADDR: "127.0.0.1:5001"
          TEST_STATE_DIR: ${{ runner.temp }}
        run: cargo test -p distrox-lib


  # We need some "accummulation" job here because bors fails (timeouts) to
  # listen on matrix builds.
  # Hence, we have some kind of dummy here that bors can listen on
  ci-success:
    name: CI
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs:
      - check
      - check-flake
      - test-lib
    steps:
      - name: CI succeeded
        run: exit 0

